import { useEffect } from 'react';
import { Button, ColorModeScript, theme, useColorMode } from '@chakra-ui/react'
import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import { AppDispatch, RootState } from '../app/store'
import styles from '../styles/Home.module.css'
import { fetchAllProducts } from '../features/guest/guestSlice';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode()
  const dispatch: AppDispatch = useDispatch();
  const products = useSelector((state : RootState) => state.guest.products);
  const loading = useSelector((state : RootState) => state.guest.loading);
  useEffect(() =>{
    dispatch(fetchAllProducts())
  }, [dispatch])
  console.log(products)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      <main className={styles.main}>
      <Button colorScheme="primary" onClick={toggleColorMode}>
        Toggle {colorMode === 'light' ? 'Dark' : 'Light'}
      </Button>
      </main>
    </div>
  )
}
